spring.application.name=ChatApp
# comment it before push change to GitHub because render will use it (3,4,5,6)
spring.datasource.url=jdbc:mysql://localhost:3306/chatapp
spring.datasource.username=root
spring.datasource.password=746296
server.port=8081

spring.jpa.hibernate.ddl-auto=update
# comment to use localhost for testing (10)
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true