spring.application.name=ChatApp
spring.datasource.url=jdbc:mysql://localhost:3306/chatapp
spring.datasource.username=root
spring.datasource.password=746296

spring.jpahibernate.ddl-auto=update
spring.jpa,show-sql=true